(ns webchange.dev-templates.flipbook
  (:require [webchange.dev-templates :as t]
            [webchange.templates.core :as templates]
            [webchange.course.core :as core]))

(def stored-data {:audio         {},
                  :assets        [{:url "/raw/img/flipbook/next-page.png", :size 1, :type "image"}
                                  {:url "/raw/img/flipbook/prev-page.png", :size 1, :type "image"}
                                  {:url "/raw/img/flipbook/pages_1.png", :size 1, :type "image"}
                                  {:url "/raw/img/flipbook/pages_2.png", :size 1, :type "image"}
                                  {:url "/raw/img/flipbook/shadow_page.png", :size 1, :type "image"}
                                  {:url "/raw/img/flipbook/corner_left.png", :size 1, :type "image"}
                                  {:url "/raw/img/flipbook/corner_right.png", :size 1, :type "image"}
                                  {:url "/raw/img/flipbook/logo_2.png", :size 1, :type "image"}
                                  "/raw/img/flipbook/logo_2.png"
                                  nil],
                  :actions       {:start-scene        {:data [{:type "flipbook-init", :target "book"}], :type "sequence-data"},
                                  :page-5-action      {:data               [{:data [{:type "empty", :duration 0}
                                                                                    {:data        [],
                                                                                     :fill        45823,
                                                                                     :type        "text-animation",
                                                                                     :audio       nil,
                                                                                     :target      "page-text-5",
                                                                                     :animation   "color",
                                                                                     :phrase-text "eee"}],
                                                                             :type "sequence-data"}],
                                                       :type               "sequence-data",
                                                       :phrase             "page-5-action",
                                                       :concept-var        "current-word",
                                                       :editor-type        "dialog",
                                                       :phrase-description "Read page"},
                                  :next-page-click    {:data [{:type "flipbook-flip-forward", :target "book"}], :type "sequence-data"},
                                  :prev-page-click    {:data [{:type "flipbook-flip-backward", :target "book"}], :type "sequence-data"},
                                  :page-cover-action  {:data               [{:data [{:type "empty", :duration 0}
                                                                                    {:data        [],
                                                                                     :fill        45823,
                                                                                     :type        "text-animation",
                                                                                     :audio       nil,
                                                                                     :target      "page-cover-title-text",
                                                                                     :animation   "color",
                                                                                     :phrase-text "t"}],
                                                                             :type "sequence-data"}],
                                                       :type               "sequence-data",
                                                       :phrase             "page-cover-action",
                                                       :concept-var        "current-word",
                                                       :editor-type        "dialog",
                                                       :phrase-description "Read page"},
                                  :credentials-action {:data               [{:data [{:type "empty", :duration 0}
                                                                                    {:data        [],
                                                                                     :fill        45823,
                                                                                     :type        "text-animation",
                                                                                     :audio       nil,
                                                                                     :target      "credits-page-authors-label",
                                                                                     :animation   "color",
                                                                                     :phrase-text "Written By"}],
                                                                             :type "sequence-data"}
                                                                            {:data [{:type "empty", :duration 0}
                                                                                    {:data        [],
                                                                                     :fill        45823,
                                                                                     :type        "text-animation",
                                                                                     :audio       nil,
                                                                                     :target      "credits-page-authors-0",
                                                                                     :animation   "color",
                                                                                     :phrase-text "q"}],
                                                                             :type "sequence-data"}
                                                                            {:data [{:type "empty", :duration 0}
                                                                                    {:data        [],
                                                                                     :fill        45823,
                                                                                     :type        "text-animation",
                                                                                     :audio       nil,
                                                                                     :target      "credits-page-illustrators-label",
                                                                                     :animation   "color",
                                                                                     :phrase-text "Illustrated By"}],
                                                                             :type "sequence-data"}
                                                                            {:data [{:type "empty", :duration 0}
                                                                                    {:data        [],
                                                                                     :fill        45823,
                                                                                     :type        "text-animation",
                                                                                     :audio       nil,
                                                                                     :target      "credits-page-illustrators-0",
                                                                                     :animation   "color",
                                                                                     :phrase-text "w"}],
                                                                             :type "sequence-data"}],
                                                       :type               "sequence-data",
                                                       :phrase             "credentials-action",
                                                       :concept-var        "current-word",
                                                       :editor-type        "dialog",
                                                       :phrase-description "Read credentials"}},
                  :objects       {:credits-page-title                 {:y           304,
                                                                       :align       "center",
                                                                       :font-size   64,
                                                                       :fill        "black",
                                                                       :editable?   {:select true},
                                                                       :type        "text",
                                                                       :x           480,
                                                                       :font-family "Lexend Deca",
                                                                       :text        "t"},
                                  :page-cover-background              {:x 0, :y 0, :fill 16777215, :type "rectangle", :width 960, :height 1080},
                                  :generic-front-page-background-back {:x 0, :y 0, :fill 16777215, :type "rectangle", :width 960, :height 1080},
                                  :generic-front-page                 {:type       "group",
                                                                       :children   ["generic-front-page-background-back" "generic-front-page-logo"],
                                                                       :generated? true,
                                                                       :transition "generic-front-page"},
                                  :page-background-5                  {:x 0, :y 0, :fill 16777215, :type "rectangle", :width 960, :height 1080},
                                  :credits-page-illustrators-label    {:y           0,
                                                                       :font-size   24,
                                                                       :fill        "black",
                                                                       :width       200,
                                                                       :editable?   {:select true},
                                                                       :type        "text",
                                                                       :chunks      [{:end 11, :start 0} {:end 14, :start 12}],
                                                                       :x           0,
                                                                       :font-family "Lexend Deca",
                                                                       :text        "Illustrated By"},
                                  :page-cover-title                   {:x        64,
                                                                       :y        880,
                                                                       :type     "group",
                                                                       :children ["page-cover-title-text" "page-cover-authors" "page-cover-illustrators"]},
                                  :page-5                             {:type "group", :children ["page-background-5" "page-text-background-5" "page-text-5"]},
                                  :next-page                          {:x                1787,
                                                                       :y                979,
                                                                       :src              "/raw/img/flipbook/corner_right.png",
                                                                       :type             "image",
                                                                       :actions          {:click {:id "next-page-click", :on "click", :type "action"}},
                                                                       :opacity          0.7,
                                                                       :interpreter-mode "!editor"},
                                  :page-back-filler                   {:type       "group",
                                                                       :children   ["page-back-filler-background"],
                                                                       :generated? true,
                                                                       :transition "page-cover-back"},
                                  :page-cover-back-background-border  {:fill 14342874},
                                  :page-cover-image                   {:y          436,
                                                                       :width      832,
                                                                       :editable?  {:drag      true,
                                                                                    :select    true,
                                                                                    :edit-form {:flip         true,
                                                                                                :scale        true,
                                                                                                :visible      true,
                                                                                                :select-image true,
                                                                                                :upload-image true}},
                                                                       :type       "image",
                                                                       :src        "/upload/HGBBJKONXAUWYZTG.png",
                                                                       :image-size "contain",
                                                                       :origin     {:type "center-center"},
                                                                       :x          480,
                                                                       :height     744},
                                  :book                               {:y            0,
                                                                       :transition   "book",
                                                                       :width        1920,
                                                                       :type         "flipbook",
                                                                       :next-control "next-page",
                                                                       :pages        [{:text       "page-cover-title-text",
                                                                                       :action     "page-cover-action",
                                                                                       :object     "page-cover",
                                                                                       :removable? false}
                                                                                      {:text nil, :object "generic-front-page", :removable? false}
                                                                                      {:text nil, :action "credentials-action", :object "credits-page", :removable? false}
                                                                                      {:text "page-text-5", :action "page-5-action", :object "page-5", :removable? true}
                                                                                      {:text nil, :object "page-back-filler", :removable? false, :back-cover-filler? true}
                                                                                      {:text nil, :object "page-cover-back", :removable? false}],
                                                                       :x            0,
                                                                       :prev-control "prev-page",
                                                                       :height       1080},
                                  :page-text-5                        {:y              64,
                                                                       :align          "left",
                                                                       :vertical-align "top",
                                                                       :font-size      38,
                                                                       :fill           0,
                                                                       :word-wrap      true,
                                                                       :width          832,
                                                                       :editable?      {:select true},
                                                                       :type           "text",
                                                                       :chunks         [{:end 3, :start 0}],
                                                                       :x              64,
                                                                       :font-family    "Lexend Deca",
                                                                       :height         952,
                                                                       :text           "eee"},
                                  :page-cover-back                    {:type       "group",
                                                                       :children   ["page-cover-back-background" "page-cover-back-image" "page-cover-back-license"],
                                                                       :generated? true,
                                                                       :transition "page-cover-back"},
                                  :background                         {:x 0, :y 0, :fill 16119285, :type "rectangle", :width 1920, :height 1080},
                                  :page-cover-back-background         {:x 0, :y 0, :fill 16777215, :type "rectangle", :width 960, :height 1080},
                                  :credits-page-authors-label         {:y           0,
                                                                       :font-size   24,
                                                                       :fill        "black",
                                                                       :width       200,
                                                                       :editable?   {:select true},
                                                                       :type        "text",
                                                                       :chunks      [{:end 7, :start 0} {:end 10, :start 8}],
                                                                       :x           0,
                                                                       :font-family "Lexend Deca",
                                                                       :text        "Written By"},
                                  :credits-page                       {:type       "group",
                                                                       :children   ["credits-page-background"
                                                                                    "credits-page-title"
                                                                                    "credits-page-authors"
                                                                                    "credits-page-illustrators"],
                                                                       :generated? true,
                                                                       :transition "credits-page"},
                                  :page-cover-back-license            {:y              700,
                                                                       :vertical-align "top",
                                                                       :placeholder    "Add attributions",
                                                                       :font-size      24,
                                                                       :fill           0,
                                                                       :word-wrap      true,
                                                                       :width          704,
                                                                       :editable?      {:select true},
                                                                       :type           "text",
                                                                       :x              128,
                                                                       :text           "Written by q.\n\nIllustrated by w."},
                                  :left-page-number                   {:x              64,
                                                                       :y              0,
                                                                       :fill           3289650,
                                                                       :text           "00",
                                                                       :type           "text",
                                                                       :font-size      24,
                                                                       :font-family    "Roboto",
                                                                       :vertical-align "top"},
                                  :credits-page-illustrators-0        {:y           0,
                                                                       :font-size   24,
                                                                       :fill        "black",
                                                                       :width       250,
                                                                       :editable?   {:select true},
                                                                       :type        "text",
                                                                       :chunks      [{:end 1, :start 0}],
                                                                       :x           200,
                                                                       :font-family "Lexend Deca",
                                                                       :text        "w"},
                                  :credits-page-illustrators          {:x        232,
                                                                       :y        656,
                                                                       :type     "group",
                                                                       :children ["credits-page-illustrators-label" "credits-page-illustrators-0"]},
                                  :credits-page-authors               {:x        232,
                                                                       :y        456,
                                                                       :type     "group",
                                                                       :children ["credits-page-authors-label" "credits-page-authors-0"]},
                                  :page-numbers                       {:x        0,
                                                                       :y        32,
                                                                       :type     "group",
                                                                       :visible  false,
                                                                       :children ["left-page-number" "right-page-number"]},
                                  :generic-front-page-logo            {:x         480,
                                                                       :y         450,
                                                                       :src       "/raw/img/flipbook/logo_2.png",
                                                                       :type      "image",
                                                                       :origin    {:type "center-center"},
                                                                       :editable? {:select true}},
                                  :page-cover-illustrators            {:y              125,
                                                                       :align          "left",
                                                                       :vertical-align "top",
                                                                       :font-size      24,
                                                                       :fill           0,
                                                                       :width          768.0,
                                                                       :editable?      {:select true},
                                                                       :type           "text",
                                                                       :x              0,
                                                                       :font-family    "Lexend Deca",
                                                                       :text           "Illustrated by w"},
                                  :page-text-background-5             {:x 0, :y 0, :fill 16777215, :type "rectangle", :width 960, :height 1080},
                                  :credits-page-authors-0             {:y           0,
                                                                       :font-size   24,
                                                                       :fill        "black",
                                                                       :width       250,
                                                                       :editable?   {:select true},
                                                                       :type        "text",
                                                                       :chunks      [{:end 1, :start 0}],
                                                                       :x           200,
                                                                       :font-family "Lexend Deca",
                                                                       :text        "q"},
                                  :credits-page-background            {:x 0, :y 0, :fill 16777215, :type "rectangle", :width 960, :height 1080},
                                  :prev-page                          {:x                32,
                                                                       :y                979,
                                                                       :src              "/raw/img/flipbook/corner_left.png",
                                                                       :type             "image",
                                                                       :actions          {:click {:id "prev-page-click", :on "click", :type "action"}},
                                                                       :opacity          0.7,
                                                                       :interpreter-mode "!editor"},
                                  :page-cover                         {:type       "group",
                                                                       :children   ["page-cover-background" "page-cover-image" "page-cover-title"],
                                                                       :transition "page-cover"},
                                  :page-cover-back-image              {:x         480,
                                                                       :y         350,
                                                                       :src       "/raw/img/flipbook/logo_2.png",
                                                                       :type      "image",
                                                                       :origin    {:type "center-center"},
                                                                       :editable? {:select true}},
                                  :right-page-number                  {:y              0,
                                                                       :align          "right",
                                                                       :vertical-align "top",
                                                                       :font-size      24,
                                                                       :fill           3289650,
                                                                       :type           "text",
                                                                       :x              1856,
                                                                       :font-family    "Roboto",
                                                                       :text           "01"},
                                  :page-cover-title-text              {:y              0,
                                                                       :align          "left",
                                                                       :vertical-align "top",
                                                                       :font-size      48,
                                                                       :fill           0,
                                                                       :width          768.0,
                                                                       :editable?      {:select true},
                                                                       :type           "text",
                                                                       :chunks         [{:end 1, :start 0}],
                                                                       :x              0,
                                                                       :font-family    "Lexend Deca",
                                                                       :text           "t"},
                                  :page-back-filler-background        {:x 0, :y 0, :fill 16777215, :type "rectangle", :width 960, :height 1080},
                                  :page-cover-authors                 {:y              85,
                                                                       :align          "left",
                                                                       :vertical-align "top",
                                                                       :font-size      24,
                                                                       :fill           0,
                                                                       :width          768.0,
                                                                       :editable?      {:select true},
                                                                       :type           "text",
                                                                       :x              0,
                                                                       :font-family    "Lexend Deca",
                                                                       :text           "By q"}},
                  :metadata      {:template-name    "flipbook",
                                  :stages           [{:idx 0, :name "t", :pages-idx [nil 0]}
                                                     {:idx 1, :name "Stage 1", :pages-idx [1 2]}
                                                     {:idx 2, :name "eee", :pages-idx [3 4]}
                                                     {:idx 3, :name "Stage 3", :pages-idx [5 nil]}],
                                  :stage-size       "contain",
                                  :saved-props      {:wizard {:activity-name "Book",
                                                              :cover-title   "t",
                                                              :name          "Book",
                                                              :cover-layout  "title-bottom",
                                                              :lang          "English",
                                                              :skills        [],
                                                              :illustrators  ["w"],
                                                              :course-name   "t",
                                                              :cover-image   {:src "/upload/HGBBJKONXAUWYZTG.png"},
                                                              :authors       ["q"],
                                                              :template-id   24}},
                                  :history          {:created {:activity-name "Book",
                                                               :cover-title   "t",
                                                               :name          "Book",
                                                               :cover-layout  "title-bottom",
                                                               :lang          "English",
                                                               :skills        [],
                                                               :illustrators  ["w"],
                                                               :course-name   "t",
                                                               :cover-image   {:src "/upload/HGBBJKONXAUWYZTG.png"},
                                                               :authors       ["q"],
                                                               :template-id   24},
                                                     :updated [{:data   {:text          "eee",
                                                                         :type          "page",
                                                                         :image         nil,
                                                                         :page-layout   "text-only",
                                                                         :spread-layout "text-right-top"},
                                                                :action "add-page"}
                                                               {:data nil, :action "add-empty-page"}
                                                               {:data nil, :action "add-empty-page"}
                                                               {:data nil, :action "add-empty-page"}
                                                               {:data nil, :action "add-text"}
                                                               {:data nil, :action "add-image"}
                                                               {:data {:page-number 3}, :action "add-image"}
                                                               {:data {:page-number 3}, :action "add-text"}]},
                                  :flipbook-pages   {:total 0, :current-side "right"},
                                  :actions          {:add-page       {:title   "Add page",
                                                                      :options [{:key     "type",
                                                                                 :type    "lookup",
                                                                                 :label   "Type",
                                                                                 :default "page",
                                                                                 :options [{:name "Page", :value "page"}
                                                                                           {:name    "Spread",
                                                                                            :value   "spread",
                                                                                            :enable? {:key   ["metadata" "flipbook-pages" "current-side"],
                                                                                                      :state "equal",
                                                                                                      :value "right"}}]}
                                                                                {:key        "page-layout",
                                                                                 :type       "lookup-image",
                                                                                 :label      "Page layout",
                                                                                 :default    "text-big-at-bottom",
                                                                                 :options    [{:src   "/images/templates/page_layout/text_big_at_bottom.png",
                                                                                               :value "text-big-at-bottom"}
                                                                                              {:src   "/images/templates/page_layout/text_small_at_bottom.png",
                                                                                               :value "text-small-at-bottom"}
                                                                                              {:src   "/images/templates/page_layout/only_image.png",
                                                                                               :value "image-only"}
                                                                                              {:src   "/images/templates/page_layout/text_at_top.png",
                                                                                               :value "text-at-top"}
                                                                                              {:src   "/images/templates/page_layout/text_full_page.png",
                                                                                               :value "text-only"}
                                                                                              {:src   "/images/templates/page_layout/icons_16.png",
                                                                                               :value "text-over-image-at-top"}
                                                                                              {:src   "/images/templates/page_layout/icons_17.png",
                                                                                               :value "text-over-image-at-bottom"}],
                                                                                 :conditions [{:key "type", :state "in", :value ["page"]}]}
                                                                                {:key        "spread-layout",
                                                                                 :type       "lookup-image",
                                                                                 :label      "Spread layout",
                                                                                 :default    "text-right-top",
                                                                                 :options    [{:src   "/images/templates/page_layout/spread_text_right_top.png",
                                                                                               :value "text-right-top"}
                                                                                              {:src   "/images/templates/page_layout/spread_text_right_bottom.png",
                                                                                               :value "text-right-bottom"}
                                                                                              {:src   "/images/templates/page_layout/spread_text_left_top.png",
                                                                                               :value "text-left-top"}
                                                                                              {:src   "/images/templates/page_layout/spread_text_left_bottom.png",
                                                                                               :value "text-left-bottom"}],
                                                                                 :conditions [{:key "type", :state "in", :value ["spread"]}]}
                                                                                {:key        "text",
                                                                                 :type       "string",
                                                                                 :label      "Text",
                                                                                 :conditions [{:key "page-layout", :state "not-in", :value ["image-only"]}]}
                                                                                {:key        "image",
                                                                                 :type       "image",
                                                                                 :label      "Image",
                                                                                 :conditions [{:key "page-layout", :state "not-in", :value ["text-only"]}]}]},
                                                     :add-text       {:title "Add text", :options []},
                                                     :add-image      {:title "Add image", :options []},
                                                     :remake-covers  {:title         "Remake covers",
                                                                      :options       [{:key         "cover-layout",
                                                                                       :type        "lookup-image",
                                                                                       :label       "Cover layout",
                                                                                       :options     [{:src   "/images/templates/cover_layout/title_at_top.svg",
                                                                                                      :name  "Title at top",
                                                                                                      :value "title-top"}
                                                                                                     {:src   "/images/templates/cover_layout/title_at_bottom.svg",
                                                                                                      :name  "Title at bottom",
                                                                                                      :value "title-bottom"}],
                                                                                       :description "Cover layout"}
                                                                                      {:key         "cover-title",
                                                                                       :type        "string",
                                                                                       :label       "Title",
                                                                                       :description "Cover title",
                                                                                       :placeholder "Type title here"}
                                                                                      {:key         "cover-image",
                                                                                       :type        "image",
                                                                                       :label       "Cover image",
                                                                                       :description "Cover image"}
                                                                                      {:key "authors", :max 3, :type "strings-list", :label "Authors"}
                                                                                      {:key       "illustrators",
                                                                                       :max       3,
                                                                                       :type      "strings-list",
                                                                                       :label     "Illustrators",
                                                                                       :optional? true}],
                                                                      :default-props "wizard"},
                                                     :add-empty-page {:title "Add empty page", :options []}},
                                  :template-version nil,
                                  :next-page-id     5,
                                  :flipbook-name    "book",
                                  :autostart        true,
                                  :template-id      24},
                  :triggers      {:start {:on "start", :action "start-scene"}},
                  :scene-objects [["background"] ["book"] ["prev-page" "next-page" "page-numbers"]]})

(comment
  (def test-course-slug "t-english-wqvikqzi")
  (def scene-slug "book")

  (core/get-scene-latest-version test-course-slug scene-slug)

  (core/update-activity-template! test-course-slug scene-slug t/user-id)

  (core/save-scene! test-course-slug scene-slug stored-data t/user-id)

  (t/update-activity course-slug scene-slug))
