(ns webchange.editor-v2.activity-dialogs.stub-case-2-concept-data)

(def concept-data {:id         78,
                   :name       "(a) apple",
                   :dataset-id 3,
                   :data       {:dialog-field-e51a7576-061f-4e94-bbd6-936fc7df466c {:data [{:data [{:data           [{:type "empty", :duration 0}
                                                                                                                     {:end         27.42,
                                                                                                                      :data        [{:end   25.5,
                                                                                                                                     :anim  "talk",
                                                                                                                                     :start 24.81}
                                                                                                                                    {:end   26.819762,
                                                                                                                                     :anim  "talk",
                                                                                                                                     :start 26.310959}
                                                                                                                                    {:end   27.42,
                                                                                                                                     :anim  "talk",
                                                                                                                                     :start 26.82}],
                                                                                                                      :type        "animation-sequence",
                                                                                                                      :audio       "/upload/VEQRANHKKEMOIUFU.mp3",
                                                                                                                      :start       24.81,
                                                                                                                      :target      "senora-vaca",
                                                                                                                      :duration    2.610000000000003,
                                                                                                                      :phrase-text "curve, line down"}],
                                                                                                    :type           "sequence-data",
                                                                                                    :concept-action true}
                                                                                                   {:data [{:type "empty", :duration 0}
                                                                                                           {:id "redraw-letter", :type "action"}],
                                                                                                    :type "sequence-data"}],
                                                                                            :type "parallel"}],
                                                                                    :type "sequence-data"},
                                :dialog-field-45d4b490-d167-4992-bf64-3487e8dbd862 {:data [{:data [{:type "empty", :duration 1000}
                                                                                                   {:end         34.371,
                                                                                                    :data        [],
                                                                                                    :type        "animation-sequence",
                                                                                                    :audio       "/upload/VEQRANHKKEMOIUFU.mp3",
                                                                                                    :start       33.871,
                                                                                                    :target      "senora-vaca",
                                                                                                    :duration    0.5,
                                                                                                    :phrase-text "A"}],
                                                                                            :type "sequence-data"}],
                                                                                    :type "sequence-data"},
                                :dialog-field-2b1330ce-7745-4a8e-87cc-7e77398939b2 {:data [{:data [{:type "empty", :duration 0}
                                                                                                   {:end         70.021,
                                                                                                    :data        [],
                                                                                                    :type        "animation-sequence",
                                                                                                    :audio       "/upload/VEQRANHKKEMOIUFU.mp3",
                                                                                                    :start       69.691,
                                                                                                    :target      "senora-vaca",
                                                                                                    :duration    0.33,
                                                                                                    :phrase-text "/a/"}],
                                                                                            :type "sequence-data"}],
                                                                                    :type "sequence-data"},
                                :dialog-field-02c7dada-5129-47cd-9f16-31298a67dca9 {:data [{:data           [{:type "empty", :duration 500}
                                                                                                             {:end         53.001,
                                                                                                              :data        [],
                                                                                                              :type        "animation-sequence",
                                                                                                              :audio       "/upload/VEQRANHKKEMOIUFU.mp3",
                                                                                                              :start       52.594,
                                                                                                              :target      "senora-vaca",
                                                                                                              :duration    0.407,
                                                                                                              :phrase-text "/a/"}],
                                                                                            :type           "sequence-data",
                                                                                            :concept-action true}],
                                                                                    :type "sequence-data"},
                                :dialog-field-fbc892e9-258e-4a27-be9e-eb4d7011d394 {:data [{:data [{:type "empty", :duration 0}
                                                                                                   {:phrase-text "/a/",
                                                                                                    :start       43.291,
                                                                                                    :type        "animation-sequence",
                                                                                                    :duration    0.43,
                                                                                                    :region-text "a",
                                                                                                    :audio       "/upload/VEQRANHKKEMOIUFU.mp3",
                                                                                                    :target      "senora-vaca",
                                                                                                    :end         43.721,
                                                                                                    :data        []}],
                                                                                            :type "sequence-data"}],
                                                                                    :type "sequence-data"},
                                :dialog-field-136fa9c0-4bde-45a0-a7aa-f933ab1cbdeb {:data [{:data [{:type "empty", :duration 500}
                                                                                                   {:end         27.42,
                                                                                                    :type        "animation-sequence",
                                                                                                    :audio       "/upload/VEQRANHKKEMOIUFU.mp3",
                                                                                                    :start       24.81,
                                                                                                    :target      "senora-vaca",
                                                                                                    :duration    2.610000000000003,
                                                                                                    :phrase-text "curve, line down"}],
                                                                                            :type "sequence-data"}],
                                                                                    :type "sequence-data"},
                                :dialog-field-8d4ef5e3-6e37-4a69-988f-de8cf45903f9 {:data [{:data [{:type "empty", :duration 0}
                                                                                                   {:phrase-text "“a”. ",
                                                                                                    :start       22.59,
                                                                                                    :type        "animation-sequence",
                                                                                                    :duration    0.478,
                                                                                                    :region-text "a",
                                                                                                    :audio       "/upload/VEQRANHKKEMOIUFU.mp3",
                                                                                                    :target      "senora-vaca",
                                                                                                    :end         23.068,
                                                                                                    :data        []}],
                                                                                            :type "sequence-data"}],
                                                                                    :type "sequence-data"},
                                :dialog-field-7dcb4949-4ae7-4947-bdb9-e744399aef73 {:data [{:data [{:type "empty", :duration 0}
                                                                                                   {:end         39.888,
                                                                                                    :data        [],
                                                                                                    :type        "animation-sequence",
                                                                                                    :audio       "/upload/VEQRANHKKEMOIUFU.mp3",
                                                                                                    :start       39.421,
                                                                                                    :target      "senora-vaca",
                                                                                                    :duration    0.467,
                                                                                                    :phrase-text "A"}],
                                                                                            :type "sequence-data"}],
                                                                                    :type "sequence-data"}},
                   :version    3})
