(ns webchange.utils.flipbook.activity-data-mock)

(def data {:audio         {},
           :assets        [{:url "/raw/img/flipbook/next-page.png", :size 1, :type "image"}
                           {:url "/raw/img/flipbook/prev-page.png", :size 1, :type "image"}
                           {:url "/raw/img/flipbook/pages_1.png", :size 1, :type "image"}
                           {:url "/raw/img/flipbook/pages_2.png", :size 1, :type "image"}
                           {:url "/raw/img/flipbook/shadow_page.png", :size 1, :type "image"}
                           {:url "/raw/img/flipbook/corner_left.png", :size 1, :type "image"}
                           {:url "/raw/img/flipbook/corner_right.png", :size 1, :type "image"}
                           {:url "/raw/img/flipbook/logo_2.png", :size 1, :type "image"}
                           "/raw/img/flipbook/logo_2.png"
                           "/raw/img/flipbook/logo_2.png"
                           "/upload/DRMZJFRIYCFFCOME.png"],
           :skills        [],
           :actions       {:timeout-instructions        {:type     "action",
                                                         :from-var [{:var-name "timeout-instructions-action", :action-property "id"}]},
                           :dialog-timeout-instructions {:data               [{:data [{:type "empty", :duration 0}
                                                                                      {:type        "animation-sequence",
                                                                                       :audio       nil,
                                                                                       :phrase-text "New action"}],
                                                                               :type "sequence-data"}],
                                                         :type               "sequence-data",
                                                         :phrase             "Timeout instructions",
                                                         :editor-type        "dialog",
                                                         :phrase-description "Timeout instructions"},
                           :init-guide                  {:data [{:type      "set-variable",
                                                                 :var-name  "tap-instructions-action",
                                                                 :var-value "dialog-tap-instructions"}
                                                                {:type      "set-variable",
                                                                 :var-name  "timeout-instructions-action",
                                                                 :var-value "dialog-timeout-instructions"}],
                                                         :type "parallel"},
                           :next-page-click             {:data [{:type "flipbook-flip-forward", :target "book"}], :type "sequence-data"},
                           :tap-instructions            {:type "action", :from-var [{:var-name "tap-instructions-action", :action-property "id"}]},
                           :dialog-tap-instructions     {:data               [{:data [{:type "empty", :duration 0}
                                                                                      {:type "animation-sequence", :audio nil, :phrase-text "New action"}],
                                                                               :type "sequence-data"}],
                                                         :type               "sequence-data",
                                                         :phrase             "Tap instructions",
                                                         :editor-type        "dialog",
                                                         :phrase-description "Tap instructions"},
                           :start-scene                 {:data [{:type "flipbook-read-cover", :target "book"}], :type "sequence-data"},
                           :prev-page-click             {:data [{:type "flipbook-flip-backward", :target "book"}], :type "sequence-data"},
                           :credentials-action          {:data               [{:data [{:type "empty", :duration 0}
                                                                                      {:data        [],
                                                                                       :fill        45823,
                                                                                       :type        "text-animation",
                                                                                       :audio       nil,
                                                                                       :target      "credits-page-authors-label",
                                                                                       :animation   "color",
                                                                                       :phrase-text "Written By"}],
                                                                               :type "sequence-data"}
                                                                              {:data [{:type "empty", :duration 0}
                                                                                      {:data        [],
                                                                                       :fill        45823,
                                                                                       :type        "text-animation",
                                                                                       :audio       nil,
                                                                                       :target      "credits-page-authors-0",
                                                                                       :animation   "color",
                                                                                       :phrase-text "Author 1"}],
                                                                               :type "sequence-data"}
                                                                              {:data [{:type "empty", :duration 0}
                                                                                      {:data        [],
                                                                                       :fill        45823,
                                                                                       :type        "text-animation",
                                                                                       :audio       nil,
                                                                                       :target      "credits-page-authors-1",
                                                                                       :animation   "color",
                                                                                       :phrase-text "Author 2"}],
                                                                               :type "sequence-data"}
                                                                              {:data [{:type "empty", :duration 0}
                                                                                      {:data        [],
                                                                                       :fill        45823,
                                                                                       :type        "text-animation",
                                                                                       :audio       nil,
                                                                                       :target      "credits-page-illustrators-label",
                                                                                       :animation   "color",
                                                                                       :phrase-text "Illustrated By"}],
                                                                               :type "sequence-data"}
                                                                              {:data [{:type "empty", :duration 0}
                                                                                      {:data        [],
                                                                                       :fill        45823,
                                                                                       :type        "text-animation",
                                                                                       :audio       nil,
                                                                                       :target      "credits-page-illustrators-0",
                                                                                       :animation   "color",
                                                                                       :phrase-text "Illustrator 1"}],
                                                                               :type "sequence-data"}
                                                                              {:data [{:type "empty", :duration 0}
                                                                                      {:data        [],
                                                                                       :fill        45823,
                                                                                       :type        "text-animation",
                                                                                       :audio       nil,
                                                                                       :target      "credits-page-illustrators-1",
                                                                                       :animation   "color",
                                                                                       :phrase-text "Illustrator 2"}],
                                                                               :type "sequence-data"}],
                                                         :type               "sequence-data",
                                                         :phrase             "credentials-action",
                                                         :concept-var        "current-word",
                                                         :editor-type        "dialog",
                                                         :phrase-description "Authors Page"},
                           :render-scene                {:type "flipbook-init", :target "book"},
                           :page-cover-action           {:data               [{:data [{:type "empty", :duration 0}
                                                                                      {:data        [],
                                                                                       :fill        45823,
                                                                                       :type        "text-animation",
                                                                                       :audio       nil,
                                                                                       :target      "page-cover-title-text",
                                                                                       :animation   "color",
                                                                                       :phrase-text "Title"}],
                                                                               :type "sequence-data"}],
                                                         :type               "sequence-data",
                                                         :phrase             "page-cover-action",
                                                         :concept-var        "current-word",
                                                         :editor-type        "dialog",
                                                         :phrase-description "Cover Page"},
                           :page-5-action               {:data               [{:data [{:type "empty", :duration 0}
                                                                                      {:data        [],
                                                                                       :fill        45823,
                                                                                       :type        "text-animation",
                                                                                       :audio       nil,
                                                                                       :target      "page-text-5",
                                                                                       :animation   "color",
                                                                                       :phrase-text "Page 1 text"}],
                                                                               :type "sequence-data"}
                                                                              {:data [{:type "empty", :duration 0}
                                                                                      {:fill        45823,
                                                                                       :type        "text-animation",
                                                                                       :audio       nil,
                                                                                       :target      "page-5-text-4",
                                                                                       :animation   "color",
                                                                                       :phrase-text "Text"}],
                                                                               :type "sequence-data"}],
                                                         :type               "sequence-data",
                                                         :phrase             "page-5-action",
                                                         :concept-var        "current-word",
                                                         :editor-type        "dialog",
                                                         :phrase-description "Page 3"}},
           :objects       {:credits-page-title                 {:y           304,
                                                                :align       "center",
                                                                :font-size   64,
                                                                :fill        "black",
                                                                :editable?   {:select true},
                                                                :type        "text",
                                                                :x           480,
                                                                :metadata    {:page-idx 2, :display-name "Authors Page - Title"},
                                                                :font-family "Lexend Deca",
                                                                :text        "Title"},
                           :credits-page-illustrators-1        {:y           50,
                                                                :font-size   24,
                                                                :fill        "black",
                                                                :width       250,
                                                                :editable?   {:select true},
                                                                :type        "text",
                                                                :chunks      [{:end 11, :start 0} {:end 13, :start 12}],
                                                                :x           200,
                                                                :metadata    {:page-idx 2, :text-idx 6, :display-name "Authors Page - Text 6"},
                                                                :font-family "Lexend Deca",
                                                                :text        "Illustrator 2"},
                           :spine-pt-3                         {:x -30, :y 240, :fill 12501333, :path [[0 20] [30 0] [30 20] [0 40]], :type "polygon"},
                           :page-cover-background              {:x 0, :y 0, :fill 16777215, :type "rectangle", :width 960, :height 1080},
                           :generic-front-page-background-back {:x 0, :y 0, :fill 16777215, :type "rectangle", :width 960, :height 1080},
                           :generic-front-page                 {:type       "group",
                                                                :children   ["generic-front-page-background-back" "generic-front-page-logo"],
                                                                :generated? true,
                                                                :transition "generic-front-page"},
                           :page-background-5                  {:x 0, :y 0, :fill 16777215, :type "rectangle", :width 960, :height 1080},
                           :credits-page-illustrators-label    {:y           0,
                                                                :font-size   24,
                                                                :fill        "black",
                                                                :width       200,
                                                                :editable?   {:select true},
                                                                :type        "text",
                                                                :chunks      [{:end 11, :start 0} {:end 14, :start 12}],
                                                                :x           0,
                                                                :metadata    {:page-idx 2, :text-idx 4, :display-name "Authors Page - Text 4"},
                                                                :font-family "Lexend Deca",
                                                                :text        "Illustrated By"},
                           :page-cover-title                   {:x        64,
                                                                :y        150,
                                                                :type     "group",
                                                                :children ["page-cover-title-text" "page-cover-authors" "page-cover-illustrators"]},
                           :spine-pt-1                         {:x -30, :y 0, :fill 3447653, :path [[0 20] [30 0] [30 1080] [0 1060]], :type "polygon"},
                           :page-5                             {:type     "group",
                                                                :children ["page-background-5"
                                                                           "page-image-5"
                                                                           "page-text-background-5"
                                                                           "page-text-5"
                                                                           "page-5-text-4"]},
                           :next-page                          {:x                1787,
                                                                :y                979,
                                                                :src              "/raw/img/flipbook/corner_right.png",
                                                                :type             "image",
                                                                :actions          {:click {:id "next-page-click", :on "click", :type "action"}},
                                                                :opacity          0.7,
                                                                :interpreter-mode "!editor"},
                           :page-back-filler                   {:type       "group",
                                                                :children   ["page-back-filler-background"],
                                                                :generated? true,
                                                                :transition "page-cover-back"},
                           :page-cover-back-background-border  {:fill 14342874},
                           :page-cover-image                   {:y          697,
                                                                :width      832,
                                                                :editable?  {:drag      true,
                                                                             :select    true,
                                                                             :edit-form {:flip         true,
                                                                                         :scale        true,
                                                                                         :visible      true,
                                                                                         :select-image true,
                                                                                         :upload-image true}},
                                                                :type       "image",
                                                                :src        "/upload/NILWXVTRQLWYOFYT.png",
                                                                :image-size "contain",
                                                                :origin     {:type "center-center"},
                                                                :x          488,
                                                                :height     744},
                           :book                               {:y            0,
                                                                :transition   "book",
                                                                :width        1920,
                                                                :type         "flipbook",
                                                                :next-control "next-page",
                                                                :pages        [{:text       "page-cover-title-text",
                                                                                :action     "page-cover-action",
                                                                                :object     "page-cover",
                                                                                :removable? false}
                                                                               {:text nil, :object "generic-front-page", :removable? false}
                                                                               {:text nil, :action "credentials-action", :object "credits-page", :removable? false}
                                                                               {:text "page-text-5", :action "page-5-action", :object "page-5", :removable? true}
                                                                               {:text nil, :object "page-back-filler", :removable? false, :back-cover-filler? true}
                                                                               {:text nil, :object "page-cover-back", :removable? false}],
                                                                :x            0,
                                                                :prev-control "prev-page",
                                                                :height       1080},
                           :page-text-5                        {:y              810,
                                                                :align          "left",
                                                                :vertical-align "top",
                                                                :font-size      38,
                                                                :fill           0,
                                                                :word-wrap      true,
                                                                :width          832,
                                                                :editable?      {:drag true, :select true, :restrict-x true},
                                                                :type           "text",
                                                                :chunks         [{:end 4, :start 0} {:end 6, :start 5} {:end 11, :start 7}],
                                                                :x              64,
                                                                :metadata       {:page-idx 3, :text-idx 1, :display-name "Page 3 - Text 1"},
                                                                :font-family    "Lexend Deca",
                                                                :height         142,
                                                                :text           "Page 1 text"},
                           :page-cover-back                    {:type       "group",
                                                                :children   ["page-cover-back-background" "page-cover-back-image" "page-cover-back-license"],
                                                                :generated? true,
                                                                :transition "page-cover-back"},
                           :page-cover-back-background         {:x 0, :y 0, :fill 16777215, :type "rectangle", :width 960, :height 1080},
                           :spine-pt-3-2                       {:x -50, :y 260, :fill 11514404, :path [[0 30] [20 0] [20 20] [0 50]], :type "polygon"},
                           :credits-page-authors-label         {:y           0,
                                                                :font-size   24,
                                                                :fill        "black",
                                                                :width       200,
                                                                :editable?   {:select true},
                                                                :type        "text",
                                                                :chunks      [{:end 7, :start 0} {:end 10, :start 8}],
                                                                :x           0,
                                                                :metadata    {:page-idx 2, :text-idx 1, :display-name "Authors Page - Text 1"},
                                                                :font-family "Lexend Deca",
                                                                :text        "Written By"},
                           :credits-page                       {:type       "group",
                                                                :children   ["credits-page-background"
                                                                             "credits-page-title"
                                                                             "credits-page-authors"
                                                                             "credits-page-illustrators"],
                                                                :generated? true,
                                                                :transition "credits-page"},
                           :credits-page-authors-1             {:y           50,
                                                                :font-size   24,
                                                                :fill        "black",
                                                                :width       250,
                                                                :editable?   {:select true},
                                                                :type        "text",
                                                                :chunks      [{:end 6, :start 0} {:end 8, :start 7}],
                                                                :x           200,
                                                                :metadata    {:page-idx 2, :text-idx 3, :display-name "Authors Page - Text 3"},
                                                                :font-family "Lexend Deca",
                                                                :text        "Author 2"},
                           :page-cover-back-license            {:y              700,
                                                                :vertical-align "top",
                                                                :placeholder    "Add attributions",
                                                                :font-size      24,
                                                                :fill           0,
                                                                :word-wrap      true,
                                                                :width          704,
                                                                :editable?      {:select true},
                                                                :type           "text",
                                                                :x              128,
                                                                :metadata       {:display-name "Back Cover Page - License"},
                                                                :text           "Written by Author 1, Author 2.

                                            Illustrated by Illustrator 1, Illustrator 2."},
                           :left-page-number                   {:y              0,
                                                                :vertical-align "top",
                                                                :font-size      24,
                                                                :fill           3289650,
                                                                :type           "text",
                                                                :x              64,
                                                                :metadata       {:text-animation-target? false},
                                                                :font-family    "Roboto",
                                                                :text           "00"},
                           :credits-page-illustrators-0        {:y           0,
                                                                :font-size   24,
                                                                :fill        "black",
                                                                :width       250,
                                                                :editable?   {:select true},
                                                                :type        "text",
                                                                :chunks      [{:end 11, :start 0} {:end 13, :start 12}],
                                                                :x           200,
                                                                :metadata    {:page-idx 2, :text-idx 5, :display-name "Authors Page - Text 5"},
                                                                :font-family "Lexend Deca",
                                                                :text        "Illustrator 1"},
                           :credits-page-illustrators          {:x        232,
                                                                :y        656,
                                                                :type     "group",
                                                                :children ["credits-page-illustrators-label"
                                                                           "credits-page-illustrators-0"
                                                                           "credits-page-illustrators-1"]},
                           :credits-page-authors               {:x        232,
                                                                :y        456,
                                                                :type     "group",
                                                                :children ["credits-page-authors-label"
                                                                           "credits-page-authors-0"
                                                                           "credits-page-authors-1"]},
                           :spine-pt-4                         {:x -30, :y 840, :fill 12501333, :path [[0 20] [30 40] [30 20] [0 0]], :type "polygon"},
                           :page-numbers                       {:x        0,
                                                                :y        32,
                                                                :type     "group",
                                                                :visible  false,
                                                                :children ["left-page-number" "right-page-number"]},
                           :spine-pt-2                         {:x -50, :y 0, :fill 1867082, :path [[0 50] [20 20] [20 1060] [0 1030]], :type "polygon"},
                           :generic-front-page-logo            {:x         480,
                                                                :y         450,
                                                                :src       "/raw/img/flipbook/logo_2.png",
                                                                :type      "image",
                                                                :origin    {:type "center-center"},
                                                                :editable? {:select true}},
                           :page-cover-illustrators            {:y              125,
                                                                :align          "left",
                                                                :vertical-align "top",
                                                                :font-size      24,
                                                                :fill           0,
                                                                :width          768,
                                                                :editable?      {:select true},
                                                                :type           "text",
                                                                :x              0,
                                                                :metadata       {:page-idx 0, :text-idx 2, :display-name "Cover Page - Illustrators"},
                                                                :font-family    "Lexend Deca",
                                                                :text           "Illustrated by Illustrator 1, Illustrator 2"},
                           :page-text-background-5             {:x 0, :y 810, :fill 16777215, :type "rectangle", :width 960, :height 270},
                           :credits-page-authors-0             {:y           0,
                                                                :font-size   24,
                                                                :fill        "black",
                                                                :width       250,
                                                                :editable?   {:select true},
                                                                :type        "text",
                                                                :chunks      [{:end 6, :start 0} {:end 8, :start 7}],
                                                                :x           200,
                                                                :metadata    {:page-idx 2, :text-idx 2, :display-name "Authors Page - Text 2"},
                                                                :font-family "Lexend Deca",
                                                                :text        "Author 1"},
                           :page-5-text-4                      {:y              919,
                                                                :align          "left",
                                                                :vertical-align "top",
                                                                :font-size      38,
                                                                :fill           0,
                                                                :word-wrap      true,
                                                                :width          832,
                                                                :editable?      {:drag true, :select true, :restrict-x true},
                                                                :type           "text",
                                                                :chunks         [{:end 5, :start 0} {:end 10, :start 6}],
                                                                :x              64,
                                                                :metadata       {:page-idx 3, :text-idx 2, :removable? true, :display-name "Page 3 - Text 2"},
                                                                :font-family    "Lexend Deca",
                                                                :text           "Extra text"},
                           :spine                              {:x        960,
                                                                :y        0,
                                                                :type     "group",
                                                                :children ["spine-pt-1" "spine-pt-2" "spine-pt-3" "spine-pt-3-2" "spine-pt-4" "spine-pt-4-2"]},
                           :credits-page-background            {:x 0, :y 0, :fill 16777215, :type "rectangle", :width 960, :height 1080},
                           :page-image-5                       {:x          0,
                                                                :y          0,
                                                                :src        "/upload/DRMZJFRIYCFFCOME.png",
                                                                :type       "image",
                                                                :width      960,
                                                                :height     810,
                                                                :editable?  {:drag      true,
                                                                             :select    true,
                                                                             :edit-form {:flip         true,
                                                                                         :scale        true,
                                                                                         :visible      true,
                                                                                         :select-image true,
                                                                                         :upload-image true}},
                                                                :image-size "contain"},
                           :prev-page                          {:x                32,
                                                                :y                979,
                                                                :src              "/raw/img/flipbook/corner_left.png",
                                                                :type             "image",
                                                                :actions          {:click {:id "prev-page-click", :on "click", :type "action"}},
                                                                :opacity          0.7,
                                                                :interpreter-mode "!editor"},
                           :page-cover                         {:type       "group",
                                                                :children   ["page-cover-background" "page-cover-image" "page-cover-title"],
                                                                :transition "page-cover"},
                           :spine-pt-4-2                       {:x -50, :y 810, :fill 11514404, :path [[0 20] [20 50] [20 30] [0 0]], :type "polygon"},
                           :page-cover-back-image              {:x         480,
                                                                :y         350,
                                                                :src       "/raw/img/flipbook/logo_2.png",
                                                                :type      "image",
                                                                :origin    {:type "center-center"},
                                                                :editable? {:select true}},
                           :right-page-number                  {:y              0,
                                                                :align          "right",
                                                                :vertical-align "top",
                                                                :font-size      24,
                                                                :fill           3289650,
                                                                :type           "text",
                                                                :x              1856,
                                                                :metadata       {:text-animation-target? false},
                                                                :font-family    "Roboto",
                                                                :text           "01"},
                           :page-cover-title-text              {:y              0,
                                                                :align          "left",
                                                                :vertical-align "top",
                                                                :font-size      48,
                                                                :fill           0,
                                                                :width          768,
                                                                :editable?      {:select true},
                                                                :type           "text",
                                                                :chunks         [{:end 5, :start 0}],
                                                                :x              0,
                                                                :metadata       {:page-idx 0, :text-idx 1, :display-name "Cover Page - Text 1"},
                                                                :font-family    "Lexend Deca",
                                                                :text           "Title"},
                           :page-back-filler-background        {:x 0, :y 0, :fill 16777215, :type "rectangle", :width 960, :height 1080},
                           :page-cover-authors                 {:y              85,
                                                                :align          "left",
                                                                :vertical-align "top",
                                                                :font-size      24,
                                                                :fill           0,
                                                                :width          768,
                                                                :editable?      {:select true},
                                                                :type           "text",
                                                                :x              0,
                                                                :metadata       {:page-idx 0, :text-idx 1, :display-name "Cover Page - Authors"},
                                                                :font-family    "Lexend Deca",
                                                                :text           "By Author 1, Author 2"}},
           :metadata      {:template-name    "flipbook",
                           :stages           [{:idx 0, :name "Title", :pages-idx [nil 0]}
                                              {:idx 1, :name "Stage 1", :pages-idx [1 2]}
                                              {:idx 2, :name "Page 1 text", :pages-idx [3 4]}
                                              {:idx 3, :name "Stage 3", :pages-idx [5 nil]}],
                           :stage-size       "contain",
                           :saved-props      {:wizard {:activity-name "Book",
                                                       :cover-title   "Title",
                                                       :name          "Book",
                                                       :cover-layout  "title-top",
                                                       :lang          "English",
                                                       :skills        [],
                                                       :illustrators  ["Illustrator 1" "Illustrator 2"],
                                                       :course-name   "Title",
                                                       :cover-image   {:src "/upload/NILWXVTRQLWYOFYT.png"},
                                                       :authors       ["Author 1" "Author 2"],
                                                       :template-id   24}},
                           :history          {:created {:activity-name "Book",
                                                        :cover-title   "Title",
                                                        :name          "Book",
                                                        :cover-layout  "title-top",
                                                        :lang          "English",
                                                        :skills        [],
                                                        :illustrators  ["Illustrator 1" "Illustrator 2"],
                                                        :course-name   "Title",
                                                        :cover-image   {:src "/upload/NILWXVTRQLWYOFYT.png"},
                                                        :authors       ["Author 1" "Author 2"],
                                                        :template-id   24},
                                              :updated [{:data   {:text          "Page 1 text",
                                                                  :type          "page",
                                                                  :image         {:src "/upload/DRMZJFRIYCFFCOME.png"},
                                                                  :page-layout   "text-big-at-bottom",
                                                                  :spread-layout "text-right-top"},
                                                         :action "add-page"}
                                                        {:data {:page-number 3}, :action "add-text"}]},
                           :flipbook-pages   {:total 0, :current-side "right"},
                           :actions          {:add-page       {:title   "Choose layout",
                                                               :options [{:key     "type",
                                                                          :type    "lookup",
                                                                          :label   "Type",
                                                                          :default "page",
                                                                          :options [{:name "Page", :value "page"}
                                                                                    {:name    "Spread",
                                                                                     :value   "spread",
                                                                                     :enable? {:key   ["metadata" "flipbook-pages" "current-side"],
                                                                                               :state "equal",
                                                                                               :value "right"}}]}
                                                                         {:key        "page-layout",
                                                                          :type       "lookup-image",
                                                                          :label      "Page layout",
                                                                          :default    "text-big-at-bottom",
                                                                          :options    [{:src   "/images/templates/page_layout/text_big_at_bottom.png",
                                                                                        :value "text-big-at-bottom"}
                                                                                       {:src   "/images/templates/page_layout/text_small_at_bottom.png",
                                                                                        :value "text-small-at-bottom"}
                                                                                       {:src   "/images/templates/page_layout/only_image.png",
                                                                                        :value "image-only"}
                                                                                       {:src   "/images/templates/page_layout/text_at_top.png",
                                                                                        :value "text-at-top"}
                                                                                       {:src   "/images/templates/page_layout/text_full_page.png",
                                                                                        :value "text-only"}
                                                                                       {:src   "/images/templates/page_layout/icons_16.png",
                                                                                        :value "text-over-image-at-top"}
                                                                                       {:src   "/images/templates/page_layout/icons_17.png",
                                                                                        :value "text-over-image-at-bottom"}],
                                                                          :conditions [{:key "type", :state "in", :value ["page"]}]}
                                                                         {:key        "spread-layout",
                                                                          :type       "lookup-image",
                                                                          :label      "Spread layout",
                                                                          :default    "text-right-top",
                                                                          :options    [{:src   "/images/templates/page_layout/spread_text_right_top.png",
                                                                                        :value "text-right-top"}
                                                                                       {:src   "/images/templates/page_layout/spread_text_right_bottom.png",
                                                                                        :value "text-right-bottom"}
                                                                                       {:src   "/images/templates/page_layout/spread_text_left_top.png",
                                                                                        :value "text-left-top"}
                                                                                       {:src   "/images/templates/page_layout/spread_text_left_bottom.png",
                                                                                        :value "text-left-bottom"}
                                                                                       {:src   "/images/templates/page_layout/spread_image_only.png",
                                                                                        :value "image-only"}],
                                                                          :conditions [{:key "type", :state "in", :value ["spread"]}]}
                                                                         {:key        "text",
                                                                          :type       "string",
                                                                          :label      "Text",
                                                                          :conditions [{:key "page-layout", :state "not-in", :value ["image-only"]}
                                                                                       {:key "spread-layout", :state "not-in", :value ["image-only"]}]}
                                                                         {:key        "image",
                                                                          :type       "image",
                                                                          :label      "Image",
                                                                          :conditions [{:key "page-layout", :state "not-in", :value ["text-only"]}]}]},
                                              :add-text       {:title "Add text", :options []},
                                              :add-image      {:title "Add image", :options [{:key "image", :type "image", :label "Select Image"}]},
                                              :remake-covers  {:title         "Remake covers",
                                                               :options       [{:key         "cover-layout",
                                                                                :type        "lookup-image",
                                                                                :label       "Cover layout",
                                                                                :options     [{:src   "/images/templates/cover_layout/title_at_top.svg",
                                                                                               :name  "Title at top",
                                                                                               :value "title-top"}
                                                                                              {:src   "/images/templates/cover_layout/title_at_bottom.svg",
                                                                                               :name  "Title at bottom",
                                                                                               :value "title-bottom"}],
                                                                                :description "Cover layout"}
                                                                               {:key         "cover-title",
                                                                                :type        "string",
                                                                                :label       "Title",
                                                                                :description "Cover title",
                                                                                :placeholder "Type title here"}
                                                                               {:key         "cover-image",
                                                                                :type        "image",
                                                                                :label       "Cover image",
                                                                                :description "Cover image"}
                                                                               {:key "authors", :max 3, :type "strings-list", :label "Authors"}
                                                                               {:key       "illustrators",
                                                                                :max       3,
                                                                                :type      "strings-list",
                                                                                :label     "Illustrators",
                                                                                :optional? true}],
                                                               :default-props "wizard"},
                                              :add-empty-page {:title "Add empty page", :options []}},
                           :template-version nil,
                           :next-page-id     5,
                           :lip-not-sync     false,
                           :flipbook-name    "book",
                           :autostart        true,
                           :template-id      24},
           :triggers      {:guide  {:on "start", :action "init-guide"},
                           :start  {:on "start", :action "start-scene"},
                           :render {:on "render", :action "render-scene"}},
           :scene-objects [["spine" "book"] ["prev-page" "next-page" "page-numbers"]]})
