(ns webchange.sw-utils.state.resources
  (:require
    [re-frame.core :as re-frame]
    [webchange.sw-utils.state.status :as status]
    [webchange.sw-utils.message :as sw]
    [webchange.sw-utils.state.db :refer [path-to-db]]))

(re-frame/reg-fx
  :cache-course
  (fn [[course-id]]
    (sw/cache-course course-id)))

(re-frame/reg-event-fx
  ::cache-course
  [(re-frame/inject-cofx :online?)]
  (fn [{:keys [db online?]} [_ course-id]]
    (when-not (status/sync-disabled? db)
      (if online?
        {:cache-course [course-id]
         :dispatch     [::status/set-sync-status :syncing]}
        {:dispatch [::status/set-sync-status :offline]}))))


(defn synced-game-resources
  [db]
  ;(get-in db [:service-worker :synced-resources :game])
  ["/raw/audio/background/Casa.mp3"
   "/raw/audio/l1/a1/mari.mp4"
   "/raw/audio/l1/a1/vera-casa-1.mp3"
   "/raw/audio/l1/a1/vera-casa-2.mp3"
   "/raw/audio/l1/a1/vera-casa-3.mp3"
   "/raw/audio/effects/correct.mp3"
   "/raw/audio/effects/incorrect.mp3"
   "/raw/audio/effects/box-appear.mp3"
   "/raw/img/casa/background.jpg"
   "/raw/img/casa_door.png"
   "/raw/audio/l1/a1/L1_A1_Vaca_Ardilla.m4a"
   "/raw/audio/l1/a1/L1_A1_Vaca_Oso.m4a"
   "/raw/audio/l1/a1/L1_A1_Vaca_Iman.m4a"
   "/raw/audio/l1/a1/L1_A1_Vaca_Diamente.m4a"
   "/raw/audio/l1/a1/L1_A1_Vaca_Object_1_insertions.m4a"
   "/raw/audio/l1/a1/L1_A1_Vaca_Object_2_insertions.m4a"
   "/raw/audio/l1/a1/L1_A1_Vaca_Object_3_insertions.m4a"
   "/raw/img/casa/door.png"
   "/raw/audio/background/POL-daily-special-short.mp3"
   "/raw/img/library/book/background.jpg"
   "/raw/img/library/book/background2.jpg"
   "/raw/img/elements/squirrel.png"
   "/raw/img/elements/bee.png"
   "/raw/img/elements/tree.png"
   "/raw/img/elements/bear.png"
   "/raw/img/elements/ear.png"
   "/raw/img/elements/eyes.png"
   "/raw/img/elements/magnet.png"
   "/raw/img/elements/iguana.png"
   "/raw/img/elements/fire.png"
   "/raw/img/elements/grapes.png"
   "/raw/img/elements/one.png"
   "/raw/img/elements/nail.png"
   "/raw/img/elements/elephant.png"
   "/raw/img/elements/star.png"
   "/raw/img/elements/nurse.png"
   "/raw/img/elements/hand.png"
   "/raw/img/elements/monkey.png"
   "/raw/img/elements/apple.png"
   "/raw/img/elements/snake.png"
   "/raw/img/elements/sun.png"
   "/raw/img/elements/watermelon.png"
   "/raw/img/elements/ball.png"
   "/raw/img/elements/duck.png"
   "/raw/img/elements/fish.png"
   "/raw/img/elements/lion.png"
   "/raw/img/elements/lemon.png"
   "/raw/img/elements/pencil.png"
   "/raw/img/elements/tomato.png"
   "/raw/img/elements/train.png"
   "/raw/img/elements/shark.png"
   "/raw/img/elements/finger.png"
   "/raw/img/elements/dragon.png"
   "/raw/img/elements/teeth.png"
   "/raw/img/elements/frog.png"
   "/raw/img/elements/rock.png"
   "/raw/img/elements/rose.png"
   "/raw/img/elements/home.png"
   "/raw/img/elements/bed.png"
   "/raw/img/elements/car.png"
   "/raw/img/elements/comb.png"
   "/raw/img/elements/pig.png"
   "/raw/img/elements/eyebrow.png"
   "/raw/img/elements/nino.png"
   "/raw/img/elements/nest.png"
   "/raw/img/elements/orange.png"
   "/raw/img/elements/flower.png"
   "/raw/img/elements/flute.png"
   "/raw/img/elements/strawberry.png"
   "/raw/img/elements/baby.png"
   "/raw/img/elements/boat.png"
   "/raw/img/elements/whale.png"
   "/raw/img/elements/garden.png"
   "/raw/img/elements/juice.png"
   "/raw/img/elements/jamon.png"
   "/raw/img/elements/cat.png"
   "/raw/img/elements/guitar.png"
   "/raw/img/elements/chicken.png"
   "/raw/img/elements/twins.png"
   "/raw/img/elements/giant.png"
   "/raw/img/elements/sunflower.png"
   "/raw/img/elements/chocolate.png"
   "/raw/img/elements/girl.png"
   "/raw/img/elements/boy.png"
   "/raw/img/elements/ostrich.png"
   "/raw/img/elements/yam.png"
   "/raw/img/elements/knot.png"
   "/raw/img/elements/violin.png"
   "/raw/img/elements/cow.png"
   "/raw/img/elements/window.png"
   "/raw/img/elements/key.png"
   "/raw/img/elements/rain.png"
   "/raw/img/elements/cry.png"
   "/raw/img/elements/leaf.png"
   "/raw/img/elements/ice cream.png"
   "/raw/img/elements/ant.png"
   "/raw/img/elements/cheese.png"
   "/raw/img/elements/five.png"
   "/raw/img/elements/fifteen.png"
   "/raw/img/elements/boots.png"
   "/raw/img/elements/fox.png"
   "/raw/img/elements/carrot.png"
   "/raw/img/elements/kimono.png"
   "/raw/img/elements/kayak.png"
   "/raw/img/elements/koala.png"
   "/raw/img/elements/website.png"
   "/raw/img/elements/deer.png"
   "/raw/img/elements/waffles.png"
   "/raw/img/elements/yoyo.png"
   "/raw/img/elements/yogurt.png"
   "/raw/img/elements/egg_yolk.png"
   "/raw/img/elements/xylophone.png"
   "/raw/img/elements/saxophone.png"
   "/raw/img/elements/taxi.png"
   "/raw/audio/l1/a6/L1_A6_Lion_Intro.m4a"
   "/raw/audio/l1/a6/L1_A6_Lion_words.m4a"
   "/raw/audio/l1/a6/L1_A6_Vera.m4a"
   "/raw/audio/l1/a6/lion/2Mis primeras palabras.mp3"
   "/raw/audio/l1/a6/lion/2Vamos a leerlo juntos.mp3"
   "/raw/audio/l1/a6/lion/2Toca la flecha.mp3"
   "/raw/audio/l1/a6/lion/2Muy buen trabajo leyendo.mp3"
   "/raw/audio/l1/a6/lion/2La a.mp3"
   "/raw/audio/l1/a6/lion/2La i.mp3"
   "/raw/audio/l1/a6/lion/2La o.mp3"
   "/raw/audio/l1/a6/lion/B.mp3"
   "/raw/audio/l1/a6/lion/C.mp3"
   "/raw/audio/l1/a6/lion/Ch.mp3"
   "/raw/audio/l1/a6/lion/D.mp3"
   "/raw/audio/l1/a6/lion/E.mp3"
   "/raw/audio/l1/a6/lion/F.mp3"
   "/raw/audio/l1/a6/lion/G.mp3"
   "/raw/audio/l1/a6/lion/H.mp3"
   "/raw/audio/l1/a6/lion/J.mp3"
   "/raw/audio/l1/a6/lion/K.mp3"
   "/raw/audio/l1/a6/lion/L.mp3"
   "/raw/audio/l1/a6/lion/LL.mp3"
   "/raw/audio/l1/a6/lion/M.mp3"
   "/raw/audio/l1/a6/lion/N.mp3"
   "/raw/audio/l1/a6/lion/P.mp3"
   "/raw/audio/l1/a6/lion/Qu.mp3"
   "/raw/audio/l1/a6/lion/R.mp3"
   "/raw/audio/l1/a6/lion/S.mp3"
   "/raw/audio/l1/a6/lion/T.mp3"
   "/raw/audio/l1/a6/lion/Tambien C.mp3"
   "/raw/audio/l1/a6/lion/También G.mp3"
   "/raw/audio/l1/a6/lion/U.mp3"
   "/raw/audio/l1/a6/lion/V.mp3"
   "/raw/audio/l1/a6/lion/W.mp3"
   "/raw/audio/l1/a6/lion/X.mp3"
   "/raw/audio/l1/a6/lion/Y.mp3"
   "/raw/audio/l1/a6/lion/Z.mp3"
   "/raw/audio/l1/a6/lion/Ñ.mp3"
   "/raw/img/ui/back_button_01.png"
   "/raw/audio/l1/a3/rock/Oso.m4a"
   "/raw/audio/l1/a3/vera/oso.m4a"
   "/raw/audio/l1/a3/rock/Iman.m4a"
   "/raw/audio/l1/a3/vera/iman.m4a"
   "/raw/audio/l1/a3/Mari_Level1_Activity3.m4a"
   "/raw/audio/l1/a3/rock/Ardilla.m4a"
   "/raw/audio/l1/a3/vera/ardilla.m4a"
   "/raw/img/park/swings/background.jpg"
   "/raw/img/park/swings/swings.png"
   "/raw/img/park/swings/tree.png"
   "/raw/audio/l1/a3/vera-swings.mp3"
   "/raw/audio/l1/a3/vera/ardilla.mp3"
   "/raw/audio/l1/a3/vera/bebe.mp3"
   "/raw/audio/l1/a3/rock/Bebe.m4a"
   "/raw/audio/l1/a3/rock/Bebe_ending.m4a"
   "/raw/audio/l1/a3/vera/casa.mp3"
   "/raw/audio/l1/a3/rock/Casa.m4a"
   "/raw/audio/l1/a3/vera/cepillo.mp3"
   "/raw/audio/l1/a3/rock/Cepillo.m4a"
   "/raw/audio/l1/a3/vera/chocolate.mp3"
   "/raw/audio/l1/a3/rock/Chocolate.m4a"
   "/raw/audio/l1/a3/vera/diamante.mp3"
   "/raw/audio/l1/a3/rock/Diamante.m4a"
   "/raw/audio/l1/a3/vera/elefante.mp3"
   "/raw/audio/l1/a3/rock/Elefante.m4a"
   "/raw/audio/l1/a3/vera/flor.mp3"
   "/raw/audio/l1/a3/rock/Flor.m4a"
   "/raw/audio/l1/a3/vera/gato.mp3"
   "/raw/audio/l1/a3/rock/Gato.m4a"
   "/raw/audio/l1/a3/vera/gemelo.mp3"
   "/raw/audio/l1/a3/rock/Gemelos.m4a"
   "/raw/audio/l1/a3/vera/hoja.mp3"
   "/raw/audio/l1/a3/rock/Hoja.m4a"
   "/raw/audio/l1/a3/vera/iman.mp3"
   "/raw/audio/l1/a3/vera/jardin.mp3"
   "/raw/audio/l1/a3/rock/Jardin.m4a"
   "/raw/audio/l1/a3/vera/kimono.mp3"
   "/raw/audio/l1/a3/rock/Kimono.m4a"
   "/raw/audio/l1/a3/vera/leon.mp3"
   "/raw/audio/l1/a3/rock/Leon.m4a"
   "/raw/audio/l1/a3/rock/Leon_roar.m4a"
   "/raw/audio/l1/a3/rock/Llaves.mp4"
   "/raw/audio/l1/a3/vera/llaves.mp3"
   "/raw/audio/l1/a3/vera/mano.mp3"
   "/raw/audio/l1/a3/rock/Manos.m4a"
   "/raw/audio/l1/a3/vera/nandu.mp3"
   "/raw/audio/l1/a3/rock/Nandu.m4a"
   "/raw/audio/l1/a3/vera/nino.mp3"
   "/raw/audio/l1/a3/rock/Nino.m4a"
   "/raw/audio/l1/a3/vera/oso.mp3"
   "/raw/audio/l1/a3/vera/pelota.mp3"
   "/raw/audio/l1/a3/rock/Pelota.m4a"
   "/raw/audio/l1/a3/vera/queso.mp3"
   "/raw/audio/l1/a3/rock/Queso.m4a"
   "/raw/audio/l1/a3/vera/rana.mp3"
   "/raw/audio/l1/a3/rock/Rana.m4a"
   "/raw/audio/l1/a3/vera/serpiente.mp3"
   "/raw/audio/l1/a3/rock/Serpiente.m4a"
   "/raw/audio/l1/a3/vera/tomate.mp3"
   "/raw/audio/l1/a3/rock/Tomate.m4a"
   "/raw/audio/l1/a3/vera/uvas.mp3"
   "/raw/audio/l1/a3/rock/Uvas.m4a"
   "/raw/audio/l1/a3/vera/violin.mp3"
   "/raw/audio/l1/a3/rock/Violin.m4a"
   "/raw/audio/l1/a3/vera/web.mp3"
   "/raw/audio/l1/a3/rock/Web.m4a"
   "/raw/audio/l1/a3/vera/xilofono.mp3"
   "/raw/audio/l1/a3/rock/Xylofono.m4a"
   "/raw/audio/l1/a3/rock/Xylofono_song.m4a"
   "/raw/audio/l1/a3/vera/yoyo.mp3"
   "/raw/audio/l1/a3/rock/Yoyo.m4a"
   "/raw/audio/l1/a3/vera/zapatos.mp3"
   "/raw/audio/l1/a3/rock/Zapatos.m4a"
   "/raw/audio/l1/a5/Mari_Level1_Activity5.m4a"
   "/raw/audio/l1/a5/mari.mp4"
   "/raw/audio/l1/a2/game-voice-1.mp3"
   "/raw/audio/l1/a2/game-voice-1-redo.mp3"
   "/raw/audio/l1/a2/game-voice-2.mp3"
   "/raw/audio/l1/a2/game-voice-3.mp3"
   "/raw/img/stadium/volleyball/background.jpg"
   "/raw/img/stadium/volleyball/ball.png"
   "/raw/audio/l1/a4/Mari_Level1_Activity4.m4a"
   "/raw/audio/l1/a4/mari.mp4"
   "/raw/audio/l1/a4/game-voice-set-1.mp3"
   "/raw/audio/l1/a4/game-voice-set-2.mp3"
   "/raw/audio/l1/a4/game-voice-set-3.mp3"
   "/raw/audio/l1/a4/Mari_L1_A4_Letter_1.m4a"
   "/raw/audio/l1/a4/Mari_L1_A4_Letter_2.m4a"
   "/raw/audio/l1/a4/Mari_L1_A4_Letter_3.m4a"
   "/raw/img/park/sandbox/background.jpg"
   "/raw/img/casa/painting_canvas.png"
   "/raw/img/stadium/cycling/cycle_race_bg_01.jpg"
   "/raw/img/stadium/cycling/cycle_race_bg_02.jpg"
   "/raw/img/stadium/cycling/cycle_race_bg_03.jpg"
   "/raw/audio/l1/a8/Mari_L1_A8.m4a"
   "/raw/audio/l1/a8/mari.mp4"
   "/raw/audio/l1/a2/Mari_Level1_Activity2.m4a"
   "/raw/img/park/see-saw/background.jpg"
   "/raw/img/park/see-saw/saw_01.png"
   "/raw/img/park/see-saw/saw_02.png"
   "/raw/img/park/see-saw/saw_03.png"
   "/raw/img/library/painting-tablet/background.jpg"
   "/raw/img/library/painting-tablet/brush.png"
   "/raw/img/library/painting-tablet/felt-tip.png"
   "/raw/img/library/painting-tablet/pencil.png"
   "/raw/img/library/painting-tablet/eraser.png"
   "/raw/audio/background/Map.mp3"
   "/raw/img/map/background.jpg"
   "/raw/img/map/casa_01.png"
   "/raw/img/map/casa_02.png"
   "/raw/img/map/feria_01.png"
   "/raw/img/map/feria_02.png"
   "/raw/img/map/feria_03.png"
   "/raw/img/map/feria_locked.png"
   "/raw/img/map/Biblioteca_Enabled.png"
   "/raw/img/map/Cine_Enabled.png"
   "/raw/img/map/Estadio_Enabled.png"
   "/raw/img/map/Parque_Enabled.png"
   "/raw/img/elements/airplane.png"
   "/raw/img/elements/spider.png"
   "/raw/img/elements/bicycle.png"
   "/raw/img/elements/mouth.png"
   "/raw/img/elements/candle.png"
   "/raw/img/elements/crocodile.png"
   "/raw/img/elements/onion.png"
   "/raw/img/elements/sausage.png"
   "/raw/img/elements/jacket.png"
   "/raw/img/elements/dinosaur.png"
   "/raw/img/elements/salad.png"
   "/raw/img/elements/building.png"
   "/raw/img/elements/fruits.png"
   "/raw/img/elements/arrow.png"
   "/raw/img/elements/earth.png"
   "/raw/img/elements/glove.png"
   "/raw/img/elements/gemstone.png"
   "/raw/img/elements/chalk.png"
   "/raw/img/elements/grass.png"
   "/raw/img/elements/egg.png"
   "/raw/img/elements/insect.png"
   "/raw/img/elements/island.png"
   "/raw/img/elements/toys.png"
   "/raw/img/elements/giraffe.png"
   "/raw/img/elements/kiwi.png"
   "/raw/img/elements/ketchup.png"
   "/raw/img/elements/moon.png"
   "/raw/img/elements/milk.png"
   "/raw/img/elements/call.png"
   "/raw/img/elements/lama.png"
   "/raw/img/elements/mama.png"
   "/raw/img/elements/mountain.png"
   "/raw/img/elements/cloud.png"
   "/raw/img/elements/black.png"
   "/raw/img/elements/8.png"
   "/raw/img/elements/sheep.png"
   "/raw/img/elements/factory.png"
   "/raw/img/elements/potatoes.png"
   "/raw/img/elements/quesadilla.png"
   "/raw/img/elements/jaw.png"
   "/raw/img/elements/mouse.png"
   "/raw/img/elements/queen.png"
   "/raw/img/elements/chair.png"
   "/raw/img/elements/soup.png"
   "/raw/img/elements/phone.png"
   "/raw/img/elements/turtle.png"
   "/raw/img/elements/unicorn.png"
   "/raw/img/elements/uniform.png"
   "/raw/img/elements/baby_cow.png"
   "/raw/img/elements/green.png"
   "/raw/img/elements/mexico.png"
   "/raw/img/elements/text.png"
   "/raw/img/elements/yak.png"
   "/raw/img/elements/yacht.png"
   "/raw/img/elements/zebra.png"
   "/raw/img/elements/skunk.png"
   "/raw/img/elements/gnocchi.png"
   "/raw/img/elements/nora.png"])

(re-frame/reg-sub
  ::synced-game-resources
  (fn [db]
    (get-in db [:service-worker :synced-resources :game])))

(re-frame/reg-event-db
  ::set-synced-game-resources
  (fn [db [_ resources]]

    (println "-------- ::set-synced-game-resources" resources)

    (assoc-in db (path-to-db [:synced-resources :game]) resources)))

(defn synced-game-endpoints
  [db]
  ["/api/courses/spanish/scenes/map"
   "/api/courses/spanish/scenes/home"
   "/api/courses/spanish/scenes/see-saw"
   "/api/courses/spanish/scenes/swings"
   "/api/courses/spanish/scenes/sandbox"
   "/api/courses/spanish/scenes/volleyball"
   "/api/courses/spanish/scenes/book"
   "/api/courses/spanish/scenes/cycling"
   "/api/courses/spanish/scenes/painting-tablet"])

(re-frame/reg-event-db
  ::sync-game-data
  (fn [_ [_ data]]
    (println "::add-game-resources" data)))

(re-frame/reg-event-db
  ::remove-game-data
  (fn [_ [_ data]]
    (println "::remove-game-data" data)))

;[webchange.sw-utils.message :as sw]
;(sw/get-cached-resources "course")
;(sw/set-cached-scenes {:course    "course"
;                       :scenes    {:add []}
;                       :resources {:add    []
;                                   :remove []}})
