(ns webchange.editor-v2.graph-builder.graph.phrases-graph--library-expected)

(def data {:books         {:path        [:books],
                           :entity      :object,
                           :children    [],
                           :connections #{{:previous :root, :name "click", :handler :welcome}}},
           :welcome       {:path        [:welcome],
                           :entity      :action,
                           :children    [],
                           :connections #{{:previous :books,
                                           :name     "next",
                                           :sequence :start-book-scene,
                                           :handler  :vera-agree}}},
           :start-reading {:path        [:start-reading],
                           :entity      :action,
                           :children    [],
                           :connections #{}},
           :vera-agree    {:path        [:vera-agree],
                           :entity      :action,
                           :children    [],
                           :connections #{{:previous :welcome,
                                           :name     "next",
                                           :sequence :start-book-scene,
                                           :handler  :start-reading}}}})
