UPDATE users SET email = concat(id, 'not-exists') where email is null;
--;;
UPDATE users SET password = concat(id, 'not-exists') where password is null;
--;;
ALTER TABLE users ALTER COLUMN email SET NOT NULL;
--;;
ALTER TABLE users ALTER COLUMN password SET NOT NULL;
--;;
ALTER TABLE students DROP CONSTRAINT school_access_code_key;
--;;
ALTER TABLE students DROP COLUMN access_code;
--;;
ALTER TABLE students DROP COLUMN school_id;
--;;
ALTER TABLE students DROP COLUMN gender;
--;;
ALTER TABLE students DROP COLUMN date_of_birth;
--;;
ALTER TABLE classes DROP COLUMN school_id;
--;;
DROP TABLE teachers;
--;;
DROP TABLE schools;