/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.kaldi;

public class VoskJNI {

    static {
        System.loadLibrary("vosk_jni");
    }

  public final static native long new_Model(String jarg1);
  public final static native void delete_Model(long jarg1);
  public final static native long new_SpkModel(String jarg1);
  public final static native void delete_SpkModel(long jarg1);
  public final static native long new_KaldiRecognizer__SWIG_0(long jarg1, Model jarg1_, float jarg2);
  public final static native long new_KaldiRecognizer__SWIG_1(long jarg1, Model jarg1_, long jarg2, SpkModel jarg2_, float jarg3);
  public final static native long new_KaldiRecognizer__SWIG_2(long jarg1, Model jarg1_, float jarg2, String jarg3);
  public final static native void delete_KaldiRecognizer(long jarg1);
  public final static native boolean KaldiRecognizer_AcceptWaveform(long jarg1, KaldiRecognizer jarg1_, byte[] jarg2, int jarg3);
  public final static native String KaldiRecognizer_Result(long jarg1, KaldiRecognizer jarg1_);
  public final static native String KaldiRecognizer_PartialResult(long jarg1, KaldiRecognizer jarg1_);
  public final static native String KaldiRecognizer_FinalResult(long jarg1, KaldiRecognizer jarg1_);
  public final static native void SetLogLevel(int jarg1);
}
